---
title: "Data Visualisation"
author: "Camilo Mayorquín"
date: "March 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

--------------------------------------------------------
# First steps - aesthetics
--------------------------------------------------------

```{r mpg}
library(tidyverse)

# Engine size vs fuel efficiency
ggplot(data = mpg) +
  geom_point(mapping = aes(x=displ,y=hwy,color=class))
# cars with big engines use more fuel
# besides color there is alpha, size and shape
```



```{r }
# All points same color, 'color' must be outside mapping
ggplot(data = mpg) +
  geom_point(mapping = aes(x=displ,y=hwy),color='blue')
```

--------------------------------------------------------
# Facets
--------------------------------------------------------

```{r}
# Same plor for every class
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```

```{r}
# Facet combination of two variables (discrete)
ggplot(data = mpg) +
  geom_point(mapping = aes(x=displ,y=hwy)) +
  facet_grid(drv~cyl)
# Graph for each cyl and drv
```

```{r}
# Face against one variable only (also discrete)
ggplot(data = mpg) +
  geom_point(mapping = aes(x=displ,y=hwy)) +
  facet_grid(.~cyl)
```

```{r}
# Face wrap allows to use same axis for stacked plots
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ cyl, nrow = 2)
```

--------------------------------------------------------
# Geometric objects - geom
--------------------------------------------------------

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy))
```

```{r}
# Same plot as before but with different geom
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x=displ,y=hwy))
```

```{r}
# Two geoms in the same graph with local mapping
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x=displ,y=hwy,linetype=drv,color=drv))+
  geom_point(mapping = aes(x=displ,y=hwy,color=drv))
```

```{r}
# Same result using 'group' as 'linetype' but better
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x=displ,y=hwy,group=drv,color=drv))
```

```{r}
# Two geoms again with improvement
# To avoid code duplication, pass mapping to ggplot(), it will treat it as global
ggplot(data = mpg, mapping = aes(x=displ,y=hwy))+
  geom_point()+
  geom_smooth()
```

```{r}
# Display different aesthetics in different layers
ggplot(data = mpg,mapping = aes(x=displ,y=hwy))+
  geom_point(mapping = aes(color=class))+
  geom_smooth()
```

```{r}
# Same idea as before but with different data
ggplot(data = mpg,mapping = aes(x=displ,y=hwy))+
  geom_point(mapping = aes(color=class))+
  geom_smooth(data = filter(mpg, class=='subcompact'),se = F)
```

```{r}
# Custom plot from exercises in book
ggplot(data = mpg, mapping = aes(x=displ,y=hwy))+
  geom_point(mapping = aes(color=drv))+
  geom_smooth(mapping = aes(linetype=drv),se = F)
```

--------------------------------------------------------
# Statistical transformations - stat
--------------------------------------------------------

```{r}
# Using the diamonds dataset that comes with ggplot
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut))
```

```{r}
# Can use geoms and stats interchangeably
# sasme plot with stat_count
ggplot(data = diamonds)+
  stat_count(mapping = aes(x=cut))
# every stat has a default geom and viceversa
```

```{r}
# bar chart where the height is already present in the data
# change the stat from default (count) to identity
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo)+
  geom_bar(mapping = aes(x=cut,y=freq),stat = 'identity')
```

```{r}
# override default aesthetics to proportion rather than count
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,y=..prop..,group=1))
```

```{r}
# summarise y values for each unique x value
ggplot(data = diamonds)+
  stat_summary(
    mapping = aes(x=cut,y=depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

```

```{r}
# geom col is used also when the height of the bar is already present in the data set
ggplot(data = demo)+
geom_col(mapping = aes(x=cut,y=freq))
```

--------------------------------------------------------
# Position adjustments
--------------------------------------------------------

```{r}
# color contour of plot
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,color=cut))
```

```{r}
# fill bars with color
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,fill=cut))
```

```{r}
# map the fill aesthetic to another variable different that the one being counted
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,fill=clarity))
```

```{r}
# using position='identity' needs transparency
ggplot(data = diamonds,mapping = aes(x=cut,fill=clarity))+
  geom_bar(alpha=1/5, position = 'identity')
```

```{r}
# or no fill
ggplot(data = diamonds,mapping = aes(x=cut,color=clarity))+
  geom_bar(fill=NA,position = 'identity')
```

```{r}
# position='fill' allows for stacked bars with same height, making it easier to compare proportions
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,fill=clarity),position='fill')
```

```{r}
# positon='dogde' places overlapping objects directly beside one another
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x=cut,fill=clarity),position='dodge')
```

```{r}
# Lastly, for overcoming the problem of overplotting in a scatterplot, it can be used position='jitter' to add a small amout of random noise to each point
ggplot(data = mpg)+
  geom_point(mapping = aes(x=displ,y=hwy),position = 'jitter')
# Allows for more revealing plots in large scale
```

--------------------------------------------------------
# Coordinate systems
--------------------------------------------------------

```{r}
# Default boxplot, discrete vs continous
ggplot(data = mpg,mapping = aes(x=class,y=hwy))+
  geom_boxplot()
```

```{r}
# Flip coordinate system
ggplot(data = mpg,mapping = aes(x=class,y=hwy))+
  geom_boxplot()+
  coord_flip()
```

```{r}
# Quick glance at spatial data
nz <- map_data('nz')

ggplot(data = nz,mapping = aes(x = long,y=lat,group=group))+
  geom_polygon(fill='white',color='black')
```

```{r}
# coord_quickmap sets the aspect ratio correctly
# plus add colors

ggplot(data = nz,mapping = aes(x = long,y=lat,group=group))+
  geom_polygon(fill=nz$group,color='black') +
  coord_quickmap()
```


```{r}
# Polar coordinates reveal a connection between a bar chart and a Coxcomb chart
bar <- ggplot(data = diamonds)+
  geom_bar(
    mapping = aes(x = cut,fill=cut),
    show.legend = F,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x=NULL,y=NULL)
```

```{r}
# Bar chart with fipled coordinates
bar + coord_flip()
```

```{r}
# Bar chart (Coxcomb?) with polar coordinates
bar + coord_polar()
```


```{r}
# EXCERCISE
# Turn stacked bar chart into pie chart
# First the satcked bar chart
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x = cut,fill=clarity))
```

```{r}
# Attempt of pie chart from previous graph
ggplot(data = diamonds)+
  geom_bar(mapping = aes(x = cut,fill=clarity),position='fill')+
  coord_polar(theta = 'x')
```

```{r}
# EXCERSISE
ggplot(data = mpg,mapping = aes(x = cty,y = hwy)) +
  geom_point()+
  geom_abline()+
  coord_fixed()

# The relation shows there is better mileage going through highways than within the city
# Coord_fixecd sets a better aspect ratio
  
```

